version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Pull Submodules
          command: |
            git submodule init
            git submodule update --remote
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install serverless
          command: sudo npm install -g serverless
      - run:
          name: Build Bundle
          command: npm run build
      - run:
          name: Setup aliyun config
          command: mkdir ~/.aliyuncli && eval "echo $'[default]\naliyun_access_key_id = $ACCESS_KEY_ID\naliyun_access_key_secret = $ACCESS_KEY_SECRET\naliyun_account_id = $ACCOUNT_ID' > ~/.aliyuncli/credentials"
      - run:
          name: Deploy Serverless
          command: serverless deploy --stage production --region ap-southeast-2

workflows:
  version: 2
  build-serverless:
    jobs:
      - build:
          filters:
            branches:
              only: master
